// Generated by https://quicktype.io

export interface ATM {
    data: Datum[];
}

export interface Datum {
    Brand: Brand[];
}

export interface Brand {
    BrandName: string;
    ATM: ATMElement[];
}

export interface ATMElement {
    Identification: string;
    SupportedLanguages: string[];
    ATMServices: string[];
    SupportedCurrencies: string[];
    MinimumPossibleAmount: string;
    Branch: Branch;
    Location: Location;
    distance?: string;
    Latitude: number;
    Longitude: number;
    Brand: string;
    IconUrl: string;
}

export interface Branch {
    Identification: string;
}

export interface Location {
    Site: Site;
    PostalAddress: PostalAddress;
}

export interface PostalAddress {
    BuildingNumber: string;
    AddressLine: string[];
    StreetName: string;
    TownName: string;
    Country: string;
    PostCode: string;
    GeoLocation: GeoLocation;
}

export interface GeoLocation {
    GeographicCoordinates: GeographicCoordinates;
}

export interface GeographicCoordinates {
    Latitude: string;
    Longitude: string;
}

export interface Site {
    Name: string;
}
